### ISSUE TITLE
Arduino "In" Menu is bugged

### ISSUE THREAD

**Issue by SavenySix** [technologiescollege/BlocklyArduino_AIO#7]
I just started with blockly and discovered this issue in the "in" menu in the arduino section.
![buggers](https://user-images.githubusercontent.com/103146008/162063076-fb5cf2a3-b3a6-4de8-94c2-9c4da6ff2cc3.PNG)
i tryed reloading the page, changing the zoom / resolution and used Edge instead of opera / opera gx browser
i analyzed the site and it looks like the elements are not bugged all in the same spot because i cant interact with them.
i hope there is an easy fix for this problem.

**Comment by SebCanet** [comment]
Hi,
thanks for trying Blockly@rduino, but this is not a bug. In fact blocks need board selction before you can use it, because it autoconfigures dropdown menu thanks to board definition (there's not the same number of pin of each board.
First, the red button, after the orange one, and finish with the green one ;-D

**Comment by SavenySix** [comment]
well i guess this makes sense ( ͡❛ ͜ʖ ͡❛)👌
